steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cep-weather-api:$COMMIT_SHA', '.']

  # Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cep-weather-api:$COMMIT_SHA']

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cep-weather-api'
      - '--image=gcr.io/$PROJECT_ID/cep-weather-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=TEST_MODE=false'
      - '--set-env-vars=WEATHER_API_KEY=${_WEATHER_API_KEY}'

# Imagens a serem armazenadas
images:
  - 'gcr.io/$PROJECT_ID/cep-weather-api:$COMMIT_SHA'

# Variáveis de substituição
substitutions:
  _WEATHER_API_KEY: '' # Definir no console do Cloud Build 