services:
  # Serviço principal da API
  app:
    build: .
    container_name: cep-weather-api
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - TEST_MODE=true 